<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="EtcdFixtures/**" CopyToOutputDirectory="PreserveNewest"/>
        <None Include="ProbesFixtures/**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\PgWorker.Core\PgWorker.Core.csproj"/>
        <ProjectReference Include="..\..\PgWorker.Etcd\PgWorker.Etcd.csproj"/>
        <ProjectReference Include="..\..\PgWorker.Docker\PgWorker.Docker.csproj"/>
        <ProjectReference Include="..\..\PgWorker.Provisioning\PgWorker.Provisioning.csproj"/>
        <ProjectReference Include="..\..\PgWorker.Moves\PgWorker.Moves.csproj"/>
        <ProjectReference Include="..\..\PgWorker.App\PgWorker.App.csproj"/>
    </ItemGroup>

</Project>
