<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Npgsql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared.Core\Shared.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Core"/>
        <Using Include="Shared.Core.Planning"/>
        <Using Include="Shared.Core.Writing"/>
    </ItemGroup>

</Project>
