<Project Sdk="Microsoft.NET.Sdk.Worker">

    <ItemGroup>
        <InternalsVisibleTo Include="PgWorker.UnitTests"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PgWorker.Core\PgWorker.Core.csproj"/>
        <ProjectReference Include="..\PgWorker.Etcd\PgWorker.Etcd.csproj"/>
        <ProjectReference Include="..\PgWorker.Docker\PgWorker.Docker.csproj"/>
        <ProjectReference Include="..\PgWorker.Provisioning\PgWorker.Provisioning.csproj"/>
        <ProjectReference Include="..\PgWorker.Moves\PgWorker.Moves.csproj"/>
        <ProjectReference Include="..\PgWorker.Backups\PgWorker.Backups.csproj"/>
        <ProjectReference Include="..\Shared.Metrics\Shared.Metrics.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Core"/>
        <Using Include="Shared.Core.Writing"/>
        <Using Include="Shared.Docker"/>
        <Using Include="Shared.Etcd.Coordination"/>
        <Using Include="Shared.Etcd.Maintenance"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared.Tls\Shared.Tls.csproj"/>
    </ItemGroup>

</Project>
