<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Http"/>
        <ProjectReference Include="..\AdminPanel.Core\AdminPanel.Core.csproj"/>
        <ProjectReference Include="..\Shared.Etcd\Shared.Etcd.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Core"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared.Tls\Shared.Tls.csproj"/>
    </ItemGroup>

</Project>
