<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="PgWorker.UnitTests"/>
        <InternalsVisibleTo Include="PgWorker.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PgWorker.Core\PgWorker.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="SSH.NET" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Core"/>
        <Using Include="Shared.Core.Planning"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared.Tls\Shared.Tls.csproj"/>
    </ItemGroup>

</Project>
