<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="FluentAssertions"/>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\KafkaWorker.Core\KafkaWorker.Core.csproj"/>
        <ProjectReference Include="..\..\KafkaWorker.Etcd\KafkaWorker.Etcd.csproj"/>
        <ProjectReference Include="..\..\KafkaWorker.Docker\KafkaWorker.Docker.csproj"/>
        <ProjectReference Include="..\..\KafkaWorker.Provisioning\KafkaWorker.Provisioning.csproj"/>
        <ProjectReference Include="..\..\KafkaWorker.App\KafkaWorker.App.csproj"/>
    </ItemGroup>

</Project>
